#!/bin/bash

uci batch << EOF

set network.lan.proto='static'
set network.lan.ipaddr='192.168.10.1'
set network.lan.netmask='255.255.255.0'

set network.wan.proto='pppoe'
set network.wan.username=''
set network.wan.password=''

commit network
EOF
